// This file is generated by CMake. Do not edit it manually.
#pragma once
#include <string>
#include <unordered_map>
#include "Resource.hpp"

LOAD_RESOURCE(cash_wav);
LOAD_RESOURCE(fard_wav);
LOAD_RESOURCE(fonts_Mojangles_Bold_ttf);
LOAD_RESOURCE(fonts_Mojangles_ttf);
LOAD_RESOURCE(fonts_Product_Sans_Bold_ttf);
LOAD_RESOURCE(fonts_Product_Sans_ttf);
LOAD_RESOURCE(fonts_Sarabun_Light_ttf);
LOAD_RESOURCE(fonts_Tenacity_Icons_ttf);
LOAD_RESOURCE(fonts_icons_v1_ttf);
LOAD_RESOURCE(seven_days_png);
LOAD_RESOURCE(smooth_off_wav);
LOAD_RESOURCE(smooth_on_wav);
LOAD_RESOURCE(yo_at_here_gif);

class ResourceLoader {
public:
    static inline std::unordered_map<std::string, Resource> Resources;
    static void loadResources();
};
