// This file is generated by CMake. Do not edit it manually.
#pragma once
#include <string>
#include "Resource.hpp"

LOAD_RESOURCE(fonts_Mojangles_ttf);
LOAD_RESOURCE(fonts_Sarabun_Light_ttf);
LOAD_RESOURCE(fonts_icons_v1_ttf);

class ResourceLoader {
public:
    static void loadResources();
};
