#pragma once
//
// Created by vastrakai on 7/3/2024.
//

#include <optional>
#include <vector>
#include <Utils/MemUtils.hpp>

#include <glm/glm.hpp>
#include <Utils/Structs.hpp>

enum BlockLegacyVFuncIndex {
    VFUNC_BlockLegacy_dtor,
    VFUNC_newBlockEntity,
    VFUNC_getNextBlockPermutation,
    VFUNC_clip,
    VFUNC_getCollisionShape,
    VFUNC_addCollisionShapes,
    VFUNC_getAABB,
    VFUNC_addAABBs,
    VFUNC_getOutline,
    VFUNC_getVisualShapeInWorld,
    VFUNC_getVisualShape,
    VFUNC_getUIShape,
    VFUNC_getLiquidClipVolume,
    VFUNC_isObstructingChests,
    VFUNC_randomlyModifyPosition_int,
    VFUNC_randomlyModifyPosition_void,
    VFUNC_onProjectileHit,
    VFUNC_onLightningHit,
    VFUNC_hasVariableLighting,
    VFUNC_isStrippable,
    VFUNC_getStrippedBlock,
    VFUNC_canProvideSupport,
    VFUNC_canProvideMultifaceSupport,
    VFUNC_canConnect,
    VFUNC_isMovingBlock,
    VFUNC_tryGetCopperBehavior,
    VFUNC_canDamperVibrations,
    VFUNC_canOccludeVibrations,
    VFUNC_isStemBlock,
    VFUNC_isContainerBlock,
    VFUNC_isCraftingBlock,
    VFUNC_isWaterBlocking,
    VFUNC_isFenceBlock,
    VFUNC_isFenceGateBlock,
    VFUNC_isThinFenceBlock,
    VFUNC_isWallBlock,
    VFUNC_isStairBlock,
    VFUNC_isSlabBlock,
    VFUNC_isDoubleSlabBlock,
    VFUNC_isDoorBlock,
    VFUNC_isRailBlock,
    VFUNC_isButtonBlock,
    VFUNC_isLeverBlock,
    VFUNC_isCandleCakeBlock,
    VFUNC_isMultifaceBlock,
    VFUNC_isSignalSource,
    VFUNC_canBeOriginalSurface,
    VFUNC_isSilentWhenJumpingOff,
    VFUNC_isValidAuxValue,
    VFUNC_canFillAtPos,
    VFUNC_sanitizeFillBlock,
    VFUNC_onFillBlock,
    VFUNC_getDirectSignal,
    VFUNC_canBeDestroyedByWaterSpread,
    VFUNC_waterSpreadCausesSpawn,
    VFUNC_canContainLiquid,
    VFUNC_getRequiredMedium,
    VFUNC_shouldConnectToRedstone,
    VFUNC_handlePrecipitation,
    VFUNC_canBeUsedInCommands,
    VFUNC_checkIsPathable,
    VFUNC_shouldDispense,
    VFUNC_dispense,
    VFUNC_transformOnFall,
    VFUNC_onRedstoneUpdate,
    VFUNC_onMove,
    VFUNC_detachesOnPistonMove,
    VFUNC_movedByPiston,
    VFUNC_onStructureBlockPlace,
    VFUNC_onStructureNeighborBlockPlace,
    VFUNC_setupRedstoneComponent,
    VFUNC_getRedstoneProperty,
    VFUNC_updateEntityAfterFallOn,
    VFUNC_isBounceBlock,
    VFUNC_isPreservingMediumWhenPlaced,
    VFUNC_isFilteredOut,
    VFUNC_canRenderSelectionOverlay,
    VFUNC_ignoreEntitiesOnPistonMove,
    VFUNC_onFertilized,
    VFUNC_mayConsumeFertilizer,
    VFUNC_canBeFertilized,
    VFUNC_mayPick_void,
    VFUNC_mayPick_bool,
    VFUNC_mayPlace_uchar,
    VFUNC_mayPlace_void,
    VFUNC_mayPlaceOn,
    VFUNC_tryToPlace,
    VFUNC_tryToTill,
    VFUNC_breaksFallingBlocks,
    VFUNC_destroy,
    VFUNC_getIgnoresDestroyPermissions,
    VFUNC_neighborChanged,
    VFUNC_getSecondPart,
    VFUNC_playerWillDestroy,
    VFUNC_asItemInstance,
    VFUNC_trySpawnResourcesOnExplosion,
    VFUNC_getPlacementBlock,
    VFUNC_calcVariant,
    VFUNC_isAttachedTo,
    VFUNC_attack,
    VFUNC_shouldTriggerEntityInside,
    VFUNC_canBeBuiltOver_BlockItem,
    VFUNC_canBeBuiltOver_void,
    VFUNC_triggerEvent,
    VFUNC_executeEvent,
    VFUNC_hasTag,
    VFUNC_getMobToSpawn,
    VFUNC_shouldStopFalling,
    VFUNC_pushesUpFallingBlocks,
    VFUNC_canHaveExtraData,
    VFUNC_hasComparatorSignal,
    VFUNC_getComparatorSignal,
    VFUNC_canSlide,
    VFUNC_canInstatick,
    VFUNC_canSpawnAt,
    VFUNC_notifySpawnedAt,
    VFUNC_causesFreezeEffect,
    VFUNC_getIconYOffset,
    VFUNC_buildDescriptionId,
    VFUNC_isAuxValueRelevantForPicking,
    VFUNC_getColor_void,
    VFUNC_getColorAtPos,
    VFUNC_getColor_Block,
    VFUNC_getColorForParticle,
    VFUNC_isSeasonTinted,
    VFUNC_onGraphicsModeChanged,
    VFUNC_getShadeBrightness,
    VFUNC_telemetryVariant,
    VFUNC_getVariant,
    VFUNC_canSpawnOn,
    VFUNC_getRenderBlock,
    VFUNC_getMappedFace,
    VFUNC_getFaceFlip,
    VFUNC_animateTickBedrockLegacy,
    VFUNC_animateTick,
    VFUNC_init,
    VFUNC_tryLegacyUpgrade,
    VFUNC_dealsContactDamage,
    VFUNC_tryGetInfested,
    VFUNC_tryGetUninfested,
    VFUNC__addHardCodedBlockComponents,
    VFUNC_onRemove,
    VFUNC_onExploded,
    VFUNC_onStandOn,
    VFUNC_onPlace,
    VFUNC_shouldTickOnSetBlock,
    VFUNC_tick,
    VFUNC_randomTick,
    VFUNC_isInteractiveBlock,
    VFUNC_use_optional,
    VFUNC_use_void,
    VFUNC_allowStateMismatchOnPlacement,
    VFUNC_canSurvive,
    VFUNC_getRenderLayer_void,
    VFUNC_getRenderLayer_BlockSource,
    VFUNC_getExtraRenderLayers,
    VFUNC_getLight,
    VFUNC_getLightEmission,
    VFUNC_getEmissiveBrightness,
    VFUNC_getMapColor,
    VFUNC__onHitByActivatingAttack,
    VFUNC_entityInside
};


class BlockLegacy {
public:
    CLASS_FIELD(uintptr_t**, mVfTable, 0x0);
    CLASS_FIELD(std::string, mTileName, 0x28);
    CLASS_FIELD(std::string, mName, 0xA0);
    CLASS_FIELD(bool, mSolid, 0x164);

    uint16_t getBlockId();
    bool mayPlaceOn(glm::ivec3 pos);
    bool isAir();
};